{
    'name': 'YouTube Playlist to eLearning',
    'version': '18.0.1.0.0',
    'summary': 'Create eLearning course and lessons from YouTube playlist',
    'description': 'Fetches videos from a YouTube playlist and saves them as courses in the Odoo eLearning platform.',
    'category': 'Website',
    'author': 'Ufuk Togay',
    'maintainer': 'Ufuk Togay',
    'website': 'https://fimeltd.com',
    'license': 'LGPL-3',
    'depends': ['website_slides'],
    'data': [
        'security/ir.model.access.csv',
        'views/res_config_settings_views.xml',
        'views/res_slide_channel_views.xml',
        'wizard/youtube_import_wizard_views.xml',
    ],
    'i18n': [
        'i18n/tr_TR.po',
        'i18n/en_US.po',
    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
}